pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./accessing-partsasist.html","Accessing PartsASIST","Trucks Customer Portal The PartsASIST web store is accessible through a link on the Volvo Trucks Customer Portal website. See the large PartsASIST...",""],
["./all-makes.html","Catalog &#62; Explore All Makes","While the Genuine Catalog is specific to the Mack and/or Volvo trucks you have in your fleet, the All Makes Catalog contains parts information for...",""],
["./approval-tree.html","Customer Services &#62; Approval Tree","On this page, you can configure limits for order approvals. You can specify multiple users as approvers, add new groups to define additional limit...",""],
["./cart.html","Cart","The cart contains all of the parts that a user is considering for purchase. In the cart, the availability of the parts is shown, along with any di...",""],
["./check-out.html","Orders &#62; Check out","The check out is the final step in submitting an order. All prices, discounts and tax are added and the final cost for the order is summarized.&#38;nb...",""],
["./company-information.html","Customer Services &#62; Company Information","This page displays company information in several sections, including:",""],
["./company-user-management.html","Customer Services &#62; Company User Management","As a primary user in PartsASIST, you can invite others from your company to join PartsASIST. You can only invite a person who has a current Trucks...",""],
["./configure-upload-file.html","Customer Services &#62; Configure Upload File","On this page, you specify some of the attributes of the order upload file. The aim is to configure this page so that it corresponds to the structu...",""],
["./contact-us.html","Customer Services &#62; Contact Us","To contact PartsASIST support, you can submit a message on this page. The figure below shows how this page appears.",""],
["./customer-services.html","Customer Services","There are a number of administrative features in PartsASIST. This chapter covers the features found in the Customer Services menu:",""],
["./edit-cart.html","Orders &#62; Edit Cart","The cart contains all of the parts that a user is considering for purchase. The cart displays the availability of the parts, pricing, quantity, an...",""],
["./fleet-catalog-(if-available).html","Catalog &#62; Fleet Catalog (if available)","The Fleet Catalog (if available) is a catalog that contains internal part numbers that are used by a specific fleet. These part numbers are equiva...",""],
["./genuine-parts.html","Catalog &#62; Shop Genuine Parts","In this topic, you&#39;ll learn about:  Filters Function group navigation Locate a part in the catalog with function groups  The top-level o...",""],
["./home-page-overview.html","Home Page","The home page is the main page for the PartsASIST web store, and is the first page that appears when the clicking the PartsASIST icon on the Truck...",""],
["./introduction.html","Introduction","This user guide provides assistance to end-user customers who visit and shop at the PartsASIST online web store.",""],
["./introduction_2.html","Welcome to PartsASIST_2","PartsASIST is a revolutionary new e-commerce tool for end-user customers of our Mack Truck and Volvo Truck dealer network. With readily searchable...",""],
["./inventory-status-.html","Catalog &#62; Inventory Status ","Inventory status icons appear on Parts Detail pages, to indicate the availability of a specific part. The table below provides explanations for al...",""],
["./local-catalog.html","Catalog &#62; Local / Dealer Catalog (if available)","Your dealer has the option to create a catalog in PartsASIST that are for parts offerings that are specific to that dealer.  These are typica...",""],
["./manage-my-fleet.html","Customer Services &#62; Manage My Fleet","Fleet information in PartsASIST is arranged by model, model year, and VIN.",""],
["./mini-cart.html","Mini cart","On the right end of the Navigation bar, hover over the small cart icon to display the mini cart. From the popup window, you can click either the E...",""],
["./my-fleet.html","Catalog &#62; My Fleet","From the Products menu, you can select the My Fleet option. This will display VINs that you have marked as favorites that have been set up in Mana...",""],
["./navigation-bar.html","Navigation bar","Below the header and logo, the navigation bar presents the following items:",""],
["./order-information.html","Orders &#62; Order Information","On this page, you can review any orders placed in PartsASIST. The Order Information page will only display RFQ and orders that were placed in Part...",""],
["./orders.html","Orders","When you make the decision to order parts, you can add one or more parts to the cart, review the contents of the cart, and check out. You can also...",""],
["./parts-detail-.html","Features","This topic explains various features that help you view information in PartsASIST. ",""],
["./product-information.html","Catalog","This chapter covers the features found in the Products menu:",""],
["./promotions.html","Catalog &#62; Promotions / Shop Special Offers","Shop Special Offers is a catalog that displays a listing of parts that are being offered with a promotional discount. The parts offered may consis...",""],
["./quick-order.html","Orders &#62; Quick Order","If you know part numbers for an order that you need to submit promptly, follow these steps to use the Quick Order feature:",""],
["./quick-start---place-an-order.html","Quick Start - Place an Order with a Part Number ","If you know the part number and want to place an order for that part, you can go directly to the Quick Order page by clicking Order &#62; Quick Ord...",""],
["./quick-start---search--filter.html","Quick Start - Search in the Search bar","In this topic, we present a tutorial that shows how to use the search field at the top of the page. You&#39;ll learn how to search for a part and filt...",""],
["./quick-start---search-from-cata.html","Quick Start - Search from Catalog Icons","Another way to search is to begin from the main page and click one of the large icons. You can choose from categories and subcategories, and then ...",""],
["./quick-start---search-in-the-ca.html","Quick Start - Search from the Product Menu","Another way to search is to begin with a top-level category in the catalog. You can then use filters to narrow the search results until you find t...",""],
["./request-for-quote.html","Orders &#62; Request For Quote","PartsASIST has an RFQ feature that is used by both the customer and their corresponding dealer. There a few different ways that an RFQ may be trig...",""],
["./saved-list.html","Orders &#62; Saved List","This feature makes it easy to reorder identical or similar orders by using order templates. An example of such an order would be the set of all fi...",""],
["./search.html","Advanced Search &#38; Filtering","As seen in the examples of the Quick Start articles in this guide, customers can use the fleet filter feature to search for parts that are for a p...",""],
["./terms-and-conditions.html","Customer Services &#62; Terms and Conditions","This page contains the terms and conditions to which all users must agree in order to use PartsASIST. The figure below depicts an example.",""],
["./upload-file.html","Orders &#62; Upload File","Most fleet mgmt systems can generate an order, and then output that order to an Excel file.",""],
["./your-profile.html","Customer Services &#62; Your Profile","This page displays user information, including:  Customer Portal/Fleet Impact user ID First and Last Name E-mail address preference for how P...",""]];
